export { default as Cart } from './Cart';
export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Payment } from './Payment';
export { default as Product } from './Product';
export { default as Register } from './Register';
export { default as Shipping } from './Shipping';
export { default as PlaceOrder } from './PlaceOrder';
export { default as Order } from './Order';
